import os
import sys
sys.path.append(os.getcwd())
import json
from collections import Counter, defaultdict

class NGramModel :

    """class responsibility: build the vocab, the n-gram counts and probabilities, save them to json files, and load them back into the instance.
    The model is a nested dict of dicts to store the n-gram probabilities"""
    """ Class Attributes:
    token_file: path to the normalized token file generated in data prep step, used to build the model
    model_path: path to save the model json file generated by this class
    vocab_path: path to save the vocab json file generated by this class
    unk_threshold: any word appearing fewer than this number of times in the token file is replaced with <UNK> in the vocab
    ngram_order: the maximum order of n-grams to count and compute probabilities for
    model: a nested dict of dicts to store the n-gram probabilities, structured as {ngram_order: {ngram_minus_next_word: {next_word: probability}}} for all n-grams at all orders.
    vocab: a list of all unique words in the token file, with words appearing fewer than UNK_THRESHOLD times replaced with <UNK>"""

    def __init__(self,  token_file, model_path, vocab_path, unk_threshold, ngram_order, model=None, vocab=None) :    
        self.token_file = token_file
        self.model_path = model_path
        self.vocab_path = vocab_path
        self.unk_threshold = unk_threshold
        self.ngram_order = ngram_order



    def build_vocab(self):
        """
        Build vocabulary by replacing words that appear fewer than
        unk_threshold times with <UNK>.
        """
        with open(self.token_file, "r", encoding="utf-8") as f:
            tokens = f.read().split()

        token_counts = Counter(tokens)

        vocab = {
            token if count >= self.unk_threshold else "<UNK>"
            for token, count in token_counts.items()
        }

        vocab.add("<UNK>")
        self.vocab = vocab
        return vocab

    def build_counts_and_probabilities(self):
        """
        Count n-grams (1..N) and compute MLE probabilities.
        Model format:
        {
            n: { context_tuple: {next_word: probability} }
        }
        """
        with open(self.token_file, "r", encoding="utf-8") as f:
            sentences = [line.split() for line in f.read().splitlines()]

        self.ngram_counts = {n: Counter() for n in range(1, self.ngram_order + 1)}
        self.context_counts = {n: Counter() for n in range(2, self.ngram_order + 1)}

        # ---- Counting pass ----
        for sent in sentences:
            for n in range(1, self.ngram_order + 1):
                for i in range(len(sent) - n + 1):
                    ngram = tuple(sent[i:i+n])
                    self.ngram_counts[n][ngram] += 1

                    if n > 1:
                        context = ngram[:-1]
                        self.context_counts[n][context] += 1

        # ---- Probability computation ----
        model = {}

        # Unigrams
        total_tokens = sum(self.ngram_counts[1].values())
        model[1] = {
            (): {word[0]: count / total_tokens
                for word, count in self.ngram_counts[1].items()}
        }

        # Higher-order ngrams
        for n in range(2, self.ngram_order + 1):
            model[n] = defaultdict(dict)
            for ngram, count in self.ngram_counts[n].items():
                context = ngram[:-1]
                word = ngram[-1]
                model[n][context][word] = count / self.context_counts[n][context]

        self.model = model
        return model

    def lookup(self, context):
        """
        Backoff lookup: try highest-order context first,
        fall back to lower orders down to unigram.
        """
        words = tuple(context.split())

        for n in range(min(len(words) + 1, self.ngram_order), 1, -1):
            ctx = words[-(n - 1):]
            if ctx in self.model[n]:
                return self.model[n][ctx]

        # fallback to unigram distribution
        return self.model[1][()]

    


    def save_model(self):
        """Save all probability tables to model.json"""
        # build model if not already built
        if not hasattr(self, "model"):
            self.build_counts_and_probabilities()

        
        serial_model = {}
        for n, table in self.model.items():
            serial_model[str(n)] = {}
            for context, dist in table.items():
                context_key = " ".join(context)  
                serial_model[str(n)][context_key] = dist

        # ensure directory exists
        model_dir = os.path.dirname(self.model_path)
        if model_dir:
            os.makedirs(model_dir, exist_ok=True)

        with open(self.model_path, "w", encoding="utf-8") as f:
            json.dump(serial_model, f, ensure_ascii=False, indent=2)


    def save_vocab(self):
        """Save vocabulary to vocab.json"""
        if not hasattr(self, "vocab"):
            self.vocab = self.build_vocab()

        # ensure directory exists
        vocab_dir = os.path.dirname(self.vocab_path)
        if vocab_dir:
            os.makedirs(vocab_dir, exist_ok=True)

        with open(self.vocab_path, "w", encoding="utf-8") as f:
            json.dump(sorted(self.vocab), f, ensure_ascii=False, indent=2)



    def load(self):
        """Load model.json and vocab.json into the instance."""
        # load vocab 
        with open(self.vocab_path, "r", encoding="utf-8") as f:
            self.vocab = set(json.load(f))

        # load model 
        with open(self.model_path, "r", encoding="utf-8") as f:
            raw_model = json.load(f)

        self.model = {}
        for n_str, table in raw_model.items():
            n = int(n_str)
            self.model[n] = {}
            for context_str, dist in table.items():
                context = tuple(context_str.split()) if context_str else ()
                self.model[n][context] = dist

    
    def main(self) :
        """Run the whole pipeline: build vocab and model, save them, and load them back into the instance."""
        self.save_vocab() # includes building vocab
        self.save_model() # includes building counts and probabilities
        self.load()

def main() :
    from dotenv import load_dotenv
    load_dotenv(dotenv_path=os.path.join(os.getcwd(), "config/.env"))
    print(os.getenv("VOCAB_PATH"))
    ngram_model = NGramModel(
        token_file=os.getenv("TRAIN_TOKENS"),
        model_path=os.getenv("MODEL"),
        vocab_path=os.getenv("VOCAB"),
        unk_threshold=int(os.getenv("UNK_THRESHOLD")),
        ngram_order=int(os.getenv("NGRAM_ORDER"))
    )
    # Trainig 
    ngram_model.main()

    # Test lookup
    print(ngram_model.lookup("the game is"))
    print(ngram_model.lookup("zzz qqq"))

if __name__ == "__main__":
    main()
        